[package]
name = "workqueue"
version = "0.1.0"
edition = "2021"

autobins = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]
test = true
path = "src/main.rs"

[dependencies]
